#!/bin/sh

case "$1" in
	start)
		./watchrotation &
		;;
	stop)
		kill `cat /var/run/watchrotation.pid`
		[ "$ID" ] || ID="`xinput list | grep 'Cando      11.6' | sed -n -e's/.*id=\([0-9]\+\).*/\1/p'`"
		[ "$ID" ] || ID="`xinput list | grep 'touchscreen' | sed -n -e's/.*id=\([0-9]\+\).*/\1/p'`"
		[ "$ID" ] || exit 0
		Y_CALIB="180 10772"
		X_CALIB="65 18854"
		xinput set-prop "$ID" "Evdev Axis Inversion" 0, 0
		xinput set-prop "$ID" "Evdev Axes Swap" 0
		xinput set-prop "$ID" "Evdev Axis Calibration" $X_CALIB $Y_CALIB
		xrandr --orientation normal 
		;;
	*)
		echo "Usage: autorotate {start|stop}"
		;;
esac
exit 0
